import os
"""
Django settings for sysmonitor project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

try:  # load .env if python-dotenv is installed; real environment variables win
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent.parent / '.env')
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'monitor.middleware.UsageTrackingMiddleware',
    'monitor.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sysmonitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'monitor.context_processors.page_counter',
                'monitor.mirror.mirror_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'sysmonitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Uptime Kuma integration ---
KUMA_URL = os.environ.get('KUMA_URL', 'http://127.0.0.1:3001')
KUMA_USERNAME = os.environ.get('KUMA_USERNAME')
KUMA_PASSWORD = os.environ.get('KUMA_PASSWORD')


# ─────────────────────────────────────────────────────────────────────────
# Remote mirror (app.bsccl.com/sysmonitor)
#
# SYSMONITOR_ROLE=local  (default) → the normal master server. Nothing below
#                                    changes its behaviour.
# SYSMONITOR_ROLE=remote           → the remote site. It shows a copy of the
#                                    master's database (pushed by
#                                    monitor/mirror_push.py), never pings or
#                                    sends notifications, and passes every change
#                                    on to the master (monitor/mirror.py).
# See MIRROR_SETUP.md.
# ─────────────────────────────────────────────────────────────────────────
SYSMONITOR_ROLE = os.environ.get('SYSMONITOR_ROLE', 'local').strip().lower()
IS_MIRROR = SYSMONITOR_ROLE == 'remote'

# Shared secret between master and remote (same value on both servers).
MIRROR_SHARED_SECRET = os.environ.get('MIRROR_SHARED_SECRET', '').strip()
MIRROR_PUBLIC_URL = os.environ.get('MIRROR_PUBLIC_URL', 'https://app.bsccl.com/sysmonitor').rstrip('/')

if MIRROR_SHARED_SECRET and not IS_MIRROR:
    # MASTER: accept signed requests forwarded from the remote through the
    # SSH tunnel (they arrive from 127.0.0.1).
    ALLOWED_HOSTS = list(ALLOWED_HOSTS) + ['127.0.0.1', 'localhost']
    MIDDLEWARE.insert(MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware') + 1,
                      'monitor.mirror.MirrorInboundMiddleware')
    DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024

if IS_MIRROR:
    # Custom backend: opens the newest snapshot named in `mirror_current`
    # (see monitor/mirror_db/base.py). NAME's folder is where snapshots live.
    DATABASES['default']['ENGINE'] = 'monitor.mirror_db'
    DATABASES['default']['NAME'] = Path(
        os.environ.get('MIRROR_DB_PATH', str(BASE_DIR / 'mirror.sqlite3')))
    MIRROR_META_PATH = Path(
        os.environ.get('MIRROR_META_PATH', str(BASE_DIR / 'mirror_meta.json')))

    # Sessions live in the browser (signed cookie), NOT in the database,
    # because the database file is replaced every ~30 seconds.
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
    SESSION_COOKIE_NAME = 'sysmonitor_mirror_session'
    CSRF_COOKIE_NAME = 'sysmonitor_mirror_csrf'

    # Behind nginx + HTTPS, served under a sub-path (e.g. /sysmonitor).
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    _prefix = os.environ.get('MIRROR_URL_PREFIX', '/sysmonitor').rstrip('/')
    if _prefix:
        SESSION_COOKIE_PATH = _prefix + '/'
        CSRF_COOKIE_PATH = _prefix + '/'
    if os.environ.get('MIRROR_HTTPS', '1') == '1':
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('MIRROR_TRUSTED_ORIGINS', '').split(',') if o]

    # Login check that never writes (see monitor/mirror_auth.py).
    AUTHENTICATION_BACKENDS = ['monitor.mirror_auth.ReadOnlyModelBackend']

    # Pass every change (and master-only pages) on to the master server.
    MIRROR_MASTER_URL = os.environ.get('MIRROR_MASTER_URL', 'http://127.0.0.1:18000')
    MIDDLEWARE.insert(MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware') + 1,
                      'monitor.mirror.MirrorForwardMiddleware')
    DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024     # profile pictures etc.
