from django.contrib import admin
from django.urls import include, path, re_path
from monitor import views

urlpatterns = [
    path('shift-report/', include('shiftreport.urls')),
    path('admin/',                            admin.site.urls),
    path('',                                  views.dashboard,         name='dashboard'),
    path('login/',                            views.login_view,        name='login'),
    path('password-reset/',                   views.password_reset_request, name='password_reset'),
    path('about/',                            views.about_view,        name='about'),
    path('manual/',                           views.manual_view,       name='manual'),
    path('manual/pdf/',                       views.manual_pdf,        name='manual_pdf'),
    path('logout/',                           views.logout_view,       name='logout'),
    path('api/status/',                       views.api_status,        name='api_status'),
    path('api/daily-summary/',               views.api_daily_summary, name='api_daily_summary'),
    path('api/report/',                       views.api_report,        name='api_report'),
    path('report/export/csv/',                 views.report_export_csv, name='report_export_csv'),
    path('report/export/pdf/',                 views.report_export_pdf, name='report_export_pdf'),
    path('users/',                            views.user_list,         name='user_list'),
    path('users/create/',                     views.user_create,       name='user_create'),
    path('users/<int:user_id>/edit/',         views.user_edit,         name='user_edit'),
    path('users/<int:user_id>/toggle-active/', views.user_toggle_active, name='user_toggle_active'),
    path('users/<int:user_id>/delete/',       views.user_delete,       name='user_delete'),
    path('page-access/',                       views.page_access_manage, name='page_access_manage'),
    path('colocation-setpoints/',              views.colocation_setpoints, name='colocation_setpoints'),
    path('devices/',                          views.device_list,       name='device_list'),
    path('devices/add/',                      views.device_create,     name='device_create'),
    path('devices/<int:device_id>/edit/',     views.device_edit,       name='device_edit'),
    path('devices/<int:device_id>/delete/',   views.device_delete,     name='device_delete'),
    path('events/',                           views.event_log,         name='event_log'),
    path('activity/',                         views.activity_log,      name='activity_log'),
    path('report/',                           views.report_view,       name='report'),
    path('uptime/',                       views.uptime_status,      name='uptime_status'),
    path('uptime/<int:monitor_id>/log/',  views.uptime_status_log,  name='uptime_status_log'),
    path('smw6pac/',                      views.pac_status_view,   name='pac_status'),
    path('sensor/',                       views.sensor_status_view, name='sensor_status'),
    path('api/sensor-status/',            views.api_sensor_status,  name='api_sensor_status'),
    path('api/sensor-history/',           views.api_sensor_history, name='api_sensor_history'),
    path('sensor/export/',                views.sensor_export_csv,  name='sensor_export_csv'),
]

# Notification routes (appended)
urlpatterns += [
    path('notifications/',                                    views.notifications_page,       name='notifications'),
    path('notifications/gateway/save/',                       views.notif_gateway_save,       name='notif_gateway_save'),
    path('notifications/gateway/test/',                       views.notif_gateway_test,       name='notif_gateway_test'),
    path('notifications/gateway/telegram-chats/',             views.notif_telegram_chats,     name='notif_telegram_chats'),
    path('notifications/recipient/add/',                      views.notif_recipient_add,      name='notif_recipient_add'),
    path('notifications/recipient/<int:rid>/edit/',           views.notif_recipient_edit,     name='notif_recipient_edit'),
    path('notifications/recipient/<int:rid>/delete/',         views.notif_recipient_delete,   name='notif_recipient_delete'),
    path('notifications/recipient/<int:rid>/test/',           views.notif_recipient_test,     name='notif_recipient_test'),
    path('notifications/recipient/<int:rid>/toggle/',         views.notif_recipient_toggle,   name='notif_recipient_toggle'),
    path('notifications/log/',                                views.notif_log,                name='notif_log'),
    path('notifications/whatsapp-health/',                     views.notif_whatsapp_health,    name='notif_whatsapp_health'),
    path('notifications/templates/',                           views.notif_message_templates,      name='notif_message_templates'),
    path('notifications/templates/save/',                      views.notif_message_template_save,  name='notif_message_template_save'),
    path('notifications/monthly-report/send-now/',             views.notif_send_monthly_report_now, name='notif_send_monthly_report_now'),
    path('genruntime/', views.generator_runtime_report, name='generator_runtime_report'),
    path('generator-fuel/', views.generator_fuel, name='generator_fuel'),
    path('generator-fuel-report/', views.generator_fuel_report, name='generator_fuel_report'),
    path('generator-cycle-audit/', views.generator_cycle_audit, name='generator_cycle_audit'),
    path('generator-cycle-audit/data/', views.generator_cycle_audit_data, name='generator_cycle_audit_data'),
    path('generator-cycle-audit/add/', views.system_manual_cycle_add, name='generator_cycle_audit_add'),
    path('generator-cycle-audit/<int:cid>/edit/', views.generator_cycle_audit_edit, name='generator_cycle_audit_edit'),
    path('generator-cycle-audit/<int:cid>/delete/', views.generator_cycle_audit_delete, name='generator_cycle_audit_delete'),
    path('generator-log/',                                     views.generator_log_page,       name='generator_log_page'),
    path('generator-log/add/',                                 views.generator_log_add,        name='generator_log_add'),
    path('generator-log/<int:eid>/edit/',                      views.generator_log_edit,       name='generator_log_edit'),
    path('generator-log/<int:eid>/delete/',                    views.generator_log_delete,     name='generator_log_delete'),
    path('maintenance/status/',                                views.maintenance_status,       name='maintenance_status'),
    path('maintenance/start/',                                  views.maintenance_start,        name='maintenance_start'),
    path('maintenance/stop/',                                   views.maintenance_stop,         name='maintenance_stop'),
    path('notification-request/',                                views.notification_request_page,        name='notification_request'),
    path('notification-request/telegram/start/',                 views.notification_request_pair_start,  name='notification_request_pair_start'),
    path('notification-request/telegram/verify/',                views.notification_request_pair_verify, name='notification_request_pair_verify'),
    path('notification-request/submit/',                         views.notification_request_submit,      name='notification_request_submit'),
    path('notification-request/change/',                         views.notification_request_change,      name='notification_request_change'),
    path('notification-request/<int:rid>/approve/',              views.notification_request_approve,     name='notification_request_approve'),
    path('notification-request/<int:rid>/delete/',               views.notification_request_delete,      name='notification_request_delete'),
    path('profile/',                                            views.profile_view,             name='profile_view'),
    path('profile/edit/',                                       views.profile_edit,             name='profile_edit'),
    path('profile/edit/save/',                                  views.profile_edit_save,        name='profile_edit_save'),
    path('profile/password/',                                   views.profile_password,         name='profile_password'),
    path('profile/password/save/',                              views.profile_password_save,    name='profile_password_save'),
    path('profile/pending-changes/',                            views.profile_pending_changes,  name='profile_pending_changes'),
    path('profile/pending-changes/<int:pid>/approve/',          views.profile_change_approve,   name='profile_change_approve'),
    path('profile/pending-changes/<int:pid>/reject/',           views.profile_change_reject,    name='profile_change_reject'),
    path('system/',                         views.system_tools,          name='system_tools'),
    path('system/state/',                    views.system_live_state,     name='system_live_state'),
    path('system/journal/',                  views.system_journal,        name='system_journal'),
    path('system/cycle/<int:cid>/action/',   views.system_cycle_action,   name='system_cycle_action'),
    path('system/manual-cycle/add/',         views.system_manual_cycle_add, name='system_manual_cycle_add'),
    path('system/restart-ping/',             views.system_restart_ping,   name='system_restart_ping'),
    path('system/restart-all/',              views.system_restart_all,    name='system_restart_all'),
    path('system/restart-all/status/',       views.system_restart_all_status, name='system_restart_all_status'),
    path('mirror/activity/',                   views.mirror_activity,       name='mirror_activity'),
    path('mirror/track/',                      views.mirror_track,          name='mirror_track'),
    path('mirror/version/',                    views.mirror_version,        name='mirror_version'),
    path('cctv/',                              views.cctv_view,             name='cctv_view'),
    path('cctv/auth/',                         views.cctv_stream_auth,      name='cctv_stream_auth'),
    path('cctv/status/',                       views.cctv_live_status,      name='cctv_live_status'),
    path('cctv-setup/',                        views.cctv_setup,            name='cctv_setup'),
    path('cctv-setup/nvr/save/',               views.cctv_nvr_save,         name='cctv_nvr_save'),
    path('cctv-setup/nvr/<int:nid>/delete/',   views.cctv_nvr_delete,       name='cctv_nvr_delete'),
    path('cctv-setup/camera/save/',            views.cctv_camera_save,      name='cctv_camera_save'),
    path('cctv-setup/camera/<int:cid>/delete/', views.cctv_camera_delete,    name='cctv_camera_delete'),
    path('system/recent-cycles/',              views.system_recent_cycles,  name='system_recent_cycles'),
]

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
# Serve uploaded profile/media files.
# Required because this SysMonitor instance runs with DEBUG=False.
urlpatterns += [
    re_path(
        r'^media/(?P<path>.*)$',
        serve,
        {'document_root': settings.MEDIA_ROOT},
    ),
]

