# Generated by Django 5.2.14 on 2026-05-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutageCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outage_start', models.DateTimeField(blank=True, null=True)),
                ('gen_start', models.DateTimeField(blank=True, null=True)),
                ('pdb_restored', models.DateTimeField(blank=True, null=True)),
                ('cycle_end', models.DateTimeField(blank=True, null=True)),
                ('pdb_duration_sec', models.IntegerField(default=0)),
                ('gen_runtime_sec', models.IntegerField(default=0)),
                ('cycle_type', models.CharField(choices=[('NORMAL', 'Normal Cycle'), ('ATS_ONLY', 'ATS Switchover Only'), ('ALARM', 'Alarm — Abnormal'), ('INCOMPLETE', 'Incomplete — In Progress'), ('CRITICAL', 'Critical — Total Failure')], default='INCOMPLETE', max_length=15)),
                ('is_complete', models.BooleanField(default=False)),
                ('alarm_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-outage_start'],
            },
        ),
    ]
