# Generated by Django 5.2.14 on 2026-06-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Maintenance Mode',
                'verbose_name_plural': 'Maintenance Mode',
            },
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='alert_alarm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='alert_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='alert_critical',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='alert_outage',
            field=models.BooleanField(default=True),
        ),
    ]
