# Generated by Django 5.2.14 on 2026-06-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_maintenancemode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=789)),
            ],
        ),
    ]
