# Generated by Django 5.2.14 on 2026-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_pageviewcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagecycle',
            name='added_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='outagecycle',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outagecycle',
            name='manual_generator',
            field=models.CharField(blank=True, choices=[('Gen-01', 'Generator 01'), ('Gen-02', 'Generator 02')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outagecycle',
            name='cycle_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Cycle'), ('ATS_ONLY', 'ATS Switchover Only'), ('ALARM', 'Alarm — Abnormal'), ('INCOMPLETE', 'Incomplete — In Progress'), ('CRITICAL', 'Critical — Total Failure'), ('MANUAL', 'Manual / Audited Entry')], default='INCOMPLETE', max_length=15),
        ),
    ]
