# Generated by Django 5.2.14 on 2026-08-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_outagecycle_added_by_outagecycle_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_usage_seconds',
            field=models.BigIntegerField(default=0),
        ),
    ]
