# Generated by Django 5.2.14 on 2026-08-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_userprofile_last_activity_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacRunState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='alert_pac_status',
            field=models.BooleanField(default=False),
        ),
    ]
