# Generated by Django 5.2.14 on 2026-09-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_pacrunstate_notificationrecipient_alert_pac_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OUTAGE_START', 'Power Outage Started'), ('CRITICAL', 'Critical — Both Devices Down'), ('ALARM', 'Alarm — Abnormal Condition'), ('COMPLETE', 'Outage Cycle Complete'), ('PAC_STATUS_CHANGE', 'SMW6PAC Status Change'), ('SENSOR_ALERT', 'Colocation Temp/Humidity Alert'), ('TEST', 'Test Message')], max_length=25, unique=True)),
                ('template_text', models.TextField(blank=True, help_text='Leave blank to use the built-in default wording.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Message Template',
            },
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='monthly_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temp_password_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('battery_pct', models.FloatField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('raw_status', models.JSONField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device_id', '-recorded_at'], name='monitor_sen_device__145a16_idx')],
            },
        ),
    ]
