# Generated by Django 5.2.14 on 2026-10-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_sensorreading_battery_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAlarmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_low', models.FloatField(blank=True, help_text='Low temperature alarm setpoint in °C.', null=True)),
                ('temperature_high', models.FloatField(blank=True, help_text='High temperature alarm setpoint in °C.', null=True)),
                ('humidity_low', models.FloatField(blank=True, help_text='Low humidity alarm setpoint in %.', null=True)),
                ('humidity_high', models.FloatField(blank=True, help_text='High humidity alarm setpoint in %.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colocation Sensor Alarm Configuration',
                'verbose_name_plural': 'Colocation Sensor Alarm Configuration',
            },
        ),
    ]
