# Generated by Django 5.2.14 on 2026-10-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_sensoralarmconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='colocation_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='colocation_data',
            field=models.BooleanField(default=False),
        ),
    ]
