# Generated by Django 5.2.14 on 2026-10-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_notificationrecipient_colocation_alarm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoralarmconfig',
            name='alarm_cooldown_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minimum minutes between repeated sensor alarm notifications.'),
        ),
    ]
