# Generated by Django 5.2.14 on 2026-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_sensoralarmconfig_alarm_cooldown_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorFuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator', models.CharField(choices=[('Gen-01', 'Generator 01'), ('Gen-02', 'Generator 02')], max_length=20)),
                ('reading_at', models.DateTimeField()),
                ('fuel_before_l', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuel_after_l', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('added_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reading_at'],
            },
        ),
    ]
