# Generated by Django 5.2.14 on 2026-10-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_generatorfuellog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='outagecycle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_manual', True)), fields=('outage_start', 'cycle_end'), name='unique_manual_cycle_start_end'),
        ),
    ]
