# Generated by Django 5.2.14 on 2026-10-07 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_outagecycle_unique_manual_cycle_start_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVNVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NOC NVR', max_length=100)),
                ('local_host', models.CharField(help_text='Local/LAN NVR IP or hostname, e.g. 192.168.1.108', max_length=255)),
                ('remote_host', models.CharField(blank=True, help_text='Public/remote NVR IP or hostname. Leave blank if remote viewing is unavailable.', max_length=255)),
                ('web_scheme', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='https', max_length=8)),
                ('web_port', models.PositiveIntegerField(default=443, help_text='NVR browser/web port.')),
                ('rtsp_port', models.PositiveIntegerField(default=554, help_text='Dahua RTSP port. Default is normally 554.')),
                ('enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CCTV NVR',
                'verbose_name_plural': 'CCTV NVRs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CCTVCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel', models.PositiveSmallIntegerField(help_text='Dahua channel number. Channel numbering starts at 1.')),
                ('stream_type', models.PositiveSmallIntegerField(choices=[(0, 'Main Stream'), (1, 'Sub Stream')], default=1, help_text='Sub Stream is recommended for multi-camera NOC viewing.')),
                ('location', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('browser_url_local', models.URLField(blank=True, help_text='Optional direct browser-compatible local live-view URL.', max_length=500)),
                ('browser_url_remote', models.URLField(blank=True, help_text='Optional direct browser-compatible remote live-view URL.', max_length=500)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='monitor.cctvnvr')),
            ],
            options={
                'verbose_name': 'CCTV Camera',
                'verbose_name_plural': 'CCTV Cameras',
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('nvr', 'channel'), name='unique_cctv_nvr_channel')],
            },
        ),
    ]
