# Generated by Django 5.2.14 on 2026-10-08 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_cctvnvr_cctvcamera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional SysMonitor account linked to this recipient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('email_alerts', models.JSONField(blank=True, default=list)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('telegram_display_name', models.CharField(blank=True, max_length=200)),
                ('telegram_verified', models.BooleanField(default=False)),
                ('telegram_alerts', models.JSONField(blank=True, default=list)),
                ('pairing_code', models.CharField(blank=True, max_length=20)),
                ('pairing_created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('admin_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Request',
                'verbose_name_plural': 'Notification Requests',
                'ordering': ['-updated_at'],
            },
        ),
    ]
