# Generated by Django 5.2.14 on 2026-10-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.PositiveIntegerField(default=1)),
                ('minor', models.PositiveIntegerField(default=1)),
                ('revision', models.PositiveBigIntegerField(default=1234)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100)),
                ('last_action', models.CharField(blank=True, max_length=200)),
                ('git_commit', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'System Revision',
                'verbose_name_plural': 'System Revision',
            },
        ),
    ]
