# Generated by Django 5.2.14 on 2026-10-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_systemrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hidden_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
