# Generated by Django 5.2.14 on 2026-10-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_userprofile_hidden_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('USER_CREATED', 'User Created'), ('USER_EDITED', 'User Edited'), ('USER_DELETED', 'User Deleted'), ('DEVICE_ADDED', 'Device Added'), ('DEVICE_EDITED', 'Device Edited'), ('DEVICE_DELETED', 'Device Deleted'), ('PROFILE_UPDATE', 'Profile Updated'), ('PROFILE_CHANGE_REQ', 'Profile Change Requested'), ('PROFILE_CHANGE_APPROVE', 'Profile Change Approved'), ('PROFILE_CHANGE_REJECT', 'Profile Change Rejected'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('NOTIF_REQUEST_SUBMIT', 'Notification Request Submitted'), ('NOTIF_REQUEST_CHANGE', 'Notification Change Requested'), ('NOTIF_REQUEST_APPROVE', 'Notification Request Approved'), ('NOTIF_REQUEST_DELETE', 'Notification Request Deleted'), ('NOTIF_TELEGRAM_PAIR', 'Telegram Notification Paired'), ('NOTIF_GATEWAY_EDIT', 'Notification Gateway Updated'), ('NOTIF_GATEWAY_TEST', 'Notification Gateway Test Sent'), ('NOTIF_RECIPIENT_ADD', 'Notification Recipient Added'), ('NOTIF_RECIPIENT_EDIT', 'Notification Recipient Edited'), ('NOTIF_RECIPIENT_DELETE', 'Notification Recipient Deleted'), ('NOTIF_RECIPIENT_TOGGLE', 'Notification Recipient Toggled'), ('NOTIF_RECIPIENT_TEST', 'Notification Recipient Test Sent'), ('GEN_SHIFT_ADD', 'Generator Shift Added'), ('GEN_SHIFT_EDIT', 'Generator Shift Edited'), ('GEN_SHIFT_DELETE', 'Generator Shift Deleted'), ('GENERATOR_FUEL_ADD', 'Generator Fuel Entry Added'), ('CYCLE_CLOSE', 'Cycle Force Closed'), ('CYCLE_DELETE', 'Cycle Deleted'), ('CYCLE_MANUAL_ADD', 'Manual Cycle Added'), ('CYCLE_MANUAL_EDIT', 'Manual Cycle Edited'), ('CYCLE_MANUAL_DELETE', 'Manual Cycle Deleted'), ('COLO_SETPOINTS', 'Colocation Setpoints Updated'), ('MAINT_START', 'Maintenance Mode Started'), ('MAINT_STOP', 'Maintenance Mode Stopped'), ('SERVICE_RESTART', 'Service Restarted'), ('SERVICE_RESTART_DENIED', 'Service Restart Denied'), ('CCTV_CONFIG', 'CCTV Configuration Changed'), ('MESSAGE_TEMPLATE_EDIT', 'Message Template Updated'), ('MONTHLY_REPORT_SEND', 'Monthly Report Sent'), ('SHIFT_REPORT_DRAFT', 'Shift Report Draft Saved'), ('SHIFT_REPORT_SEND', 'Shift Report Sent'), ('SHIFT_REPORT_CONFIG', 'Shift Report Configuration Changed'), ('SHIFT_ISSUE_ADD', 'Shift Important Issue Added'), ('SHIFT_ISSUE_EDIT', 'Shift Important Issue Updated')], max_length=40),
        ),
    ]
