# Generated by Django 5.2.14 on 2026-10-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_duty_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyroster',
            name='original_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyroster',
            name='original_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='dutyroster',
            name='original_size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
