# Generated by Django 5.2.14 on 2026-10-08 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email', models.EmailField(blank=True, help_text='Mandatory To recipient for every normal shift report.', max_length=254)),
                ('mandatory_cc', models.TextField(blank=True, help_text='Mandatory CC addresses, one per line or comma-separated. Report writers may add CC addresses but cannot remove these.')),
                ('mnoc_to', models.TextField(blank=True, help_text='Recipients for the separate MNOC night-shift email, one per line or comma-separated.')),
                ('mnoc_cc', models.TextField(blank=True, help_text='Mandatory CC recipients for the MNOC night-shift email.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Shift Report Configuration',
                'verbose_name_plural': 'Shift Report Configuration',
            },
        ),
        migrations.CreateModel(
            name='ShiftHandoverContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_handover_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Handover Contact',
                'verbose_name_plural': 'Shift Handover Contacts',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftImportantIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MONITORING', 'Monitoring'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=12)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_important_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Operational date on which this shift started.')),
                ('shift', models.CharField(choices=[('MORNING', 'Morning Shift'), ('EVENING', 'Evening Shift'), ('NIGHT', 'Night Shift')], max_length=10)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SENT', 'Sent'), ('FAILED', 'Email Failed')], default='DRAFT', max_length=12)),
                ('regular_activities', models.TextField(blank=True)),
                ('issues_observed', models.TextField(blank=True)),
                ('pending_handover', models.TextField(blank=True)),
                ('important_notes', models.TextField(blank=True)),
                ('additional_cc', models.TextField(blank=True)),
                ('outage_summary', models.JSONField(blank=True, default=dict)),
                ('generator_summary', models.JSONField(blank=True, default=dict)),
                ('sensor_summary', models.JSONField(blank=True, default=dict)),
                ('previous_day_summary', models.JSONField(blank=True, default=dict)),
                ('mnoc_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=300)),
                ('email_to', models.JSONField(blank=True, default=list)),
                ('email_cc', models.JSONField(blank=True, default=list)),
                ('email_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handover_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_shift_reports', to='shiftreport.shifthandovercontact')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_shift_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shift_start', '-id'],
                'constraints': [models.UniqueConstraint(fields=('report_date', 'shift'), name='unique_shift_report_date_shift')],
            },
        ),
    ]
