# Generated by Django 5.2.14 on 2026-10-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='main_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='mnoc_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
