# Generated by Django 5.2.14 on 2026-10-08 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftreport', '0002_shiftreport_main_email_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreportconfig',
            name='company_name',
            field=models.CharField(blank=True, default='Bangladesh Submarine Cables PLC. (BSCPLC)', max_length=200),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='mandatory_to',
            field=models.TextField(blank=True, help_text='Fixed mandatory TO addresses, one per line or comma-separated.'),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='noc_from_email',
            field=models.EmailField(blank=True, help_text='Fixed From address for Shift Report and MNOC PFE email.', max_length=254),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='noc_from_name',
            field=models.CharField(blank=True, default='SMW4 NOC (COXCLS)', max_length=150),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='noc_mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.office365.com', max_length=150),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shiftreportconfig',
            name='website',
            field=models.CharField(blank=True, default='www.bscplc.gov.bd', max_length=200),
        ),
        migrations.AlterField(
            model_name='shiftreportconfig',
            name='manager_email',
            field=models.EmailField(blank=True, help_text='Legacy manager mandatory TO address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='shiftreportconfig',
            name='mnoc_cc',
            field=models.TextField(blank=True, help_text='Mandatory CC recipients for the MNOC PFE email.'),
        ),
        migrations.CreateModel(
            name='MnocPfeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('voltage_v', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_ma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('CURRENT', 'CURRENT'), ('VOLTAGE', 'VOLTAGE'), ('OTHER', 'OTHER')], default='CURRENT', max_length=20)),
                ('remark', models.CharField(default='OK', max_length=100)),
                ('alarm_status', models.CharField(default='None', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('FAILED', 'Email Failed')], default='DRAFT', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=300)),
                ('email_to', models.JSONField(blank=True, default=list)),
                ('email_cc', models.JSONField(blank=True, default=list)),
                ('email_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_mnoc_pfe_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MNOC PFE Report',
                'verbose_name_plural': 'MNOC PFE Reports',
                'ordering': ['-report_date', '-id'],
            },
        ),
    ]
