# Generated by Django 5.2.14 on 2026-10-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftreport', '0003_shiftreportconfig_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftimportantissue',
            name='category_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shiftimportantissue',
            name='category_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shiftimportantissue',
            name='event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shiftimportantissue',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='ac_shifting',
            field=models.TextField(blank=True, default='Shifting of active AC as per rotational turn was performed.'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='bandwidth_status',
            field=models.TextField(blank=True, default='Total Capacity: 4,650 Gbps\nUsed Capacity: 2413.875 Gbps (51.91%) (Currently Carrying Traffic)\nFree Capacity: 2,236.125 Gbps (48.09%)\nAssigned Capacity: Approx. 2,725 Gbps (Ready for service)\nTotal Active Circuits: 80\n100G: 19\n10G: 51\nSTM-16: 1\nSTM-1: 9'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='cable_status',
            field=models.CharField(blank=True, default='Normal', max_length=100),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='dwdm_status',
            field=models.CharField(blank=True, default='Normal', max_length=100),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='generator_status_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='maintenance_activity',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='network_status',
            field=models.CharField(blank=True, default='Normal', max_length=100),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='pfe_status',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='rain_water_leakage',
            field=models.TextField(blank=True, default='No significant rain was observed'),
        ),
        migrations.AlterField(
            model_name='shiftimportantissue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shiftimportantissue',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ShiftReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, max_length=200)),
                ('client_vendor', models.CharField(blank=True, max_length=250)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_rows', to='shiftreport.shiftreport')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
