# Generated by Django 5.2.14 on 2026-10-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftreport', '0004_shiftimportantissue_category_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='shift_continues',
            field=models.BooleanField(default=False),
        ),
    ]
